name: Maven Build

on:
  push:
    branches:
      - master  # Change this to your main branch if needed
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo is checked out

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Temurin is a widely used JDK distribution
          java-version: '17'

      - name: Verify `pom.xml` existence
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "ERROR: pom.xml not found in the root directory!"
            exit 1
          fi

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install
